backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "body", label: "Body", widget: "markdown"}