backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Saree", "Dress", "Gown", "Lehenga"]
        }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number", min: 0 }
